apiVersion: v1
kind: Pod
metadata:
  name: redis  # Name of the pod
  labels:
    app: test
spec:
  containers:
  - name: redis  # Container name
    image: redis  # Corrected image name (official Redis image)
